var data = [
  {"Tile": "tile_carto_dark"},
  {"Tile": "tile_carto_light"},
  {"Tile": "tile_opentopomap"},
  {"Tile": "tile_hot"},
  {"Tile": "tile_woodcut"},
  {"Tile": "tile_spacestation"},
  {"Tile": "tile_digitalglobe"},
  {"Tile": "tile_runkeeper"},
  {"Tile": "tile_wheatpaste"},
  {"Tile": "tile_rl_dtm5x5"},
  {"Tile": "tile_rl_1954"},
  {"Tile": "tile_simpson"},
  {"Tile": "tile_openrailway"},
  {"Tile": "tile_guildwars2"},
  {"Tile": "tile_waze"},
  {"Tile": "tile_hydda_roads"},
  {"Tile": "tile_osm_nolabels"},
  {"Tile": "tile_ita_geo_100k"},
  {"Tile": "tile_aster_gdem_srtm"},
  {"Tile": "tile_korona_adminb"},
  {"Tile": "tile_cartodb_labels"},
  {"Tile": "tile_stamen_labels"}
];
